# These comments are here to get you started,
# and will go away upon setting the configuration
# for the first time. You can see these comments
# again by using the "configs stock" command.

# For any setting asking for an ID, you can put
# the name of it as well, and the bot will be able
# to use it just fine. Note that it will use the
# first one it finds, and it is case-sensitive.
# For example:
# modrole: "Staff"
# Will work like:
# modrole: 259199371361517569

logging:
  modlog:

staff:
  # The role ID for your admin role.
  adminrole: 
  # The role ID for your moderator role.
  modrole: 
  # The role ID for bots. This will allow bots to speak during lockdowns, and in mute channels.
  botrole: 
  # The channel ID for the Staff channel.
  staffchannel: 
  # A link to your rules. You can use channels with "<#CHANNELID>",
  # but the bot will not convert a name for you.
  rulesurl: 
  # A link to appeal bans or actions. This will be forwarded to
  # the user upon being banned by the bot.
  appealurl: 

toss:
  # The role ID to add to users when muting a user.
  tossrole: 
  # The category ID for mute sessions to be created in.
  tosscategory: 
  # The channel that the bot will send its mute notifications to.
  # If left blank, the bot will use the Staff channel instead.
  notificationchannel: 
  # The channel names that the bot will use when creating sessions.
  # You may only have up to 25.
  tosschannels:

  # The topic for each muted channel.
  tosstopic:

  # Message for tosses
  tossmsg: 

  # Message for tosses on rejoin
  tossmsg_rejoin:


reaction:
  # If the bot may automatically adjust names to be readable.
  autoreadableenable:
  
overrides:
  # To override a command for use with more roles than allowed by default,
  # or to restrict a command to certain roles, configure it here.
  # Please see the following example.
  #
  # - command: kick            # The command you want to override.
  #   roles:                   # The roles this override should apply for.
  #     - 259199371361517569
  #   restrict: false          # Whether to allow (false) or restrict this command to (true) these roles.

drive:
  folder:
  # Set the ID of the Google Drive folder that the file should be uploaded to.

metadata:
  version: 12
